### ISSUE TITLE
cannot export system blueprints using dm pkg export

### ISSUE THREAD

**Issue by l3abak** [equinor/dm-cli#69]
#### Expected Behaviour
`dm pkg export system/SIMOS 
`
should download the SIMOS package.

#### Actual Behaviour
it provides the following error.

```
Traceback (most recent call last):
  File "/home/babak/.local/bin/dm", line 432, in <module>
    cli()
  File "/home/babak/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/babak/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/babak/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/babak/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/babak/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/babak/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/babak/.local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/babak/.local/bin/dm", line 243, in export_documents
    response = export(absolute_document_ref=absolute_document_reference)
  File "/home/babak/.local/lib/python3.10/site-packages/dm_cli/dmss.py", line 58, in export
    raise ApplicationException(
dm_cli.dmss.ApplicationException
```
#### Steps to Reproduce

**Comment by KristianKjerstad** [comment]
This seems to be an issue with modelling done in the system/SIMOS package.

fixed here: https://github.com/equinor/data-modelling-storage-service/pull/385
